AWSTemplateFormatVersion: '2010-09-09'

Resources:
# Create SG(WEB)
  web:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Web Security Group'
      VpcId: xxxxxx
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        SourceSecurityGroupId: !Ref elb
      Tags:
      - Key: Name
        Value: cf-sg-web

# Create SG(Admin)
  admin:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Admin Security Group'
      VpcId: xxxxxx
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 210.227.234.114/32
      Tags:
      - Key: Name
        Value: cf-sg-admin

# Create SG(ELB)
  elb:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'ELB Security Group'
      VpcId: xxxxxx
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: cf-sg-elb
